// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/moXXcha/hiroyuki_diet_API/utils"
)

type Auth struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type InputExercise struct {
	UserID *UUID `json:"userId,omitempty"`
	Time   int   `json:"time"`
}

type InputFood struct {
	ID              UUID   `json:"id"`
	Name            string `json:"name"`
	EstimateCalorie int    `json:"estimateCalorie"`
	LastUsedDate    string `json:"lastUsedDate"`
}

type InputMeal struct {
	UserID   *UUID          `json:"userId,omitempty"`
	MealType utils.MealType `json:"mealType"`
	Foods    []*InputFood   `json:"foods"`
}

type InputProfile struct {
	UserID                  *UUID   `json:"userId,omitempty"`
	Name                    string  `json:"name"`
	Description             *string `json:"description,omitempty"`
	Age                     int     `json:"age"`
	Gender                  string  `json:"gender"`
	Weight                  int     `json:"weight"`
	Height                  int     `json:"height"`
	TargetWeight            int     `json:"targetWeight"`
	TargetDailyExerciseTime int     `json:"targetDailyExerciseTime"`
	TargetDailyCarorie      int     `json:"targetDailyCarorie"`
}

type Mutation struct {
}

type Query struct {
}

type UseItem struct {
	ItemID UUID `json:"itemId"`
	Count  int  `json:"count"`
}
