// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/moXXcha/hiroyuki_diet_API/utils"
)

type Auth struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type InputAchievement struct {
	UserID        UUID `json:"userId"`
	AchievementID UUID `json:"achievementId"`
}

type InputExercise struct {
	UserID      *UUID `json:"userId,omitempty"`
	Time        int   `json:"time"`
	IsCompleted *bool `json:"isCompleted,omitempty"`
}

type InputMeal struct {
	UserID   *UUID          `json:"userId,omitempty"`
	MealID   *UUID          `json:"mealId,omitempty"`
	MealType utils.MealType `json:"mealType"`
	Foods    []UUID         `json:"foods"`
}

type InputPostSkin struct {
	UserID UUID `json:"userId"`
	SkinID UUID `json:"skinId"`
}

type InputProfile struct {
	UserID                  UUID   `json:"userId"`
	UserName                string `json:"userName"`
	Age                     int    `json:"age"`
	Gender                  string `json:"gender"`
	Weight                  int    `json:"weight"`
	Height                  int    `json:"height"`
	TargetWeight            int    `json:"targetWeight"`
	TargetDailyExerciseTime int    `json:"targetDailyExerciseTime"`
	TargetDailyCarorie      int    `json:"targetDailyCarorie"`
}

type InputTokenAuth struct {
	UserID UUID `json:"userId"`
	Token  int  `json:"token"`
}

type InputUpdateWeight struct {
	UserID UUID `json:"userId"`
	Weight int  `json:"weight"`
}

type InputUseItem struct {
	UserID UUID `json:"userId"`
	ItemID UUID `json:"itemId"`
	Count  int  `json:"count"`
}

type Mutation struct {
}

type MutationSuccessResponse struct {
	ID *UUID `json:"id,omitempty"`
}

type Query struct {
}
