package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"

	"github.com/moXXcha/hiroyuki_diet_API/graph/model"
)

// Date is the resolver for the date field.
func (r *exerciseResolver) Date(ctx context.Context, obj *model.Exercise) (string, error) {
	return obj.Date.Format("2006-01-02"), nil
}

// LastUsedDate is the resolver for the lastUsedDate field.
func (r *foodResolver) LastUsedDate(ctx context.Context, obj *model.Food) (string, error) {
	date := obj.LastUsedDate.Format("2006-01-02")
	return date, nil
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.Auth) (string, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Auth) (string, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// CreateExercise is the resolver for the createExercise field.
func (r *mutationResolver) CreateExercise(ctx context.Context, input model.InputExercise) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: CreateExercise - createExercise"))
}

// EditExercise is the resolver for the editExercise field.
func (r *mutationResolver) EditExercise(ctx context.Context, input model.InputExercise) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: EditExercise - editExercise"))
}

// ReceiptAchievement is the resolver for the receiptAchievement field.
func (r *mutationResolver) ReceiptAchievement(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ReceiptAchievement - receiptAchievement"))
}

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.InputProfile) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: CreateProfile - createProfile"))
}

// EditProfile is the resolver for the editProfile field.
func (r *mutationResolver) EditProfile(ctx context.Context, input model.InputProfile) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: EditProfile - editProfile"))
}

// CreateMeal is the resolver for the createMeal field.
func (r *mutationResolver) CreateMeal(ctx context.Context, input model.InputMeal) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: CreateMeal - createMeal"))
}

// EditMeal is the resolver for the editMeal field.
func (r *mutationResolver) EditMeal(ctx context.Context, input model.InputMeal) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: EditMeal - editMeal"))
}

// PostSkin is the resolver for the postSkin field.
func (r *mutationResolver) PostSkin(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: PostSkin - postSkin"))
}

// UseItem is the resolver for the useItem field.
func (r *mutationResolver) UseItem(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: UseItem - useItem"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id model.UUID) (*model.User, error) {
	db := r.DB
	user := model.User{}
	userInfo, err := user.GetInfo(id, db)
	return userInfo, err
}

// Foods is the resolver for the foods field.
func (r *queryResolver) Foods(ctx context.Context) ([]*model.Food, error) {
	db := r.DB
	food := model.Food{}
	foods, err := food.GetAll(db)
	return foods, err
}

// Profile is the resolver for the profile field.
func (r *userResolver) Profile(ctx context.Context, obj *model.User) (*model.Profile, error) {
	db := r.DB
	profileModel := model.Profile{}
	profile, err := profileModel.GetInfo(obj.Id, db)
	return profile, err
}

// Exercisies is the resolver for the exercisies field.
func (r *userResolver) Exercisies(ctx context.Context, obj *model.User, offset string, limit string) ([]*model.Exercise, error) {
	db := r.DB
	exercise := model.Exercise{}

	exercises, err := exercise.GetInfo(obj.Id, offset, limit, db)
	return exercises, err
}

// Meals is the resolver for the meals field.
func (r *userResolver) Meals(ctx context.Context, obj *model.User) ([]*model.Meal, error) {
	db := r.DB
	mealModel := model.Meal{}
	meals, err := mealModel.GetAll(obj.Id, db)
	return meals, err
}

// Meal is the resolver for the meal field.
func (r *userResolver) Meal(ctx context.Context, obj *model.User, id model.UUID) (*model.Meal, error) {
	db := r.DB
	mealModel := model.Meal{}
	meal, err := mealModel.GetById(id, db)
	return meal, err
}

// Items is the resolver for the items field.
func (r *userResolver) Items(ctx context.Context, obj *model.User) ([]*model.ItemResponse, error) {
	db := r.DB
	itemModel := model.MasterItem{}
	items, err := itemModel.GetAllByUserId(obj.Id, db)
	return items, err
}

// HiroyukiSkins is the resolver for the hiroyukiSkins field.
func (r *userResolver) HiroyukiSkins(ctx context.Context, obj *model.User, usingSkin bool) ([]*model.SkinResponse, error) {
	db := r.DB
	skinModel := model.MasterHiroyukiSkin{}
	skins, err := skinModel.GetSkins(obj.Id, usingSkin, db)
	return skins, err
}

// Achievements is the resolver for the achievements field.
func (r *userResolver) Achievements(ctx context.Context, obj *model.User) ([]*model.AchievementResponse, error) {
	panic(fmt.Errorf("not implemented: Achievements - achievements"))
}

// HiroyukiVoicies is the resolver for the hiroyukiVoicies field.
func (r *userResolver) HiroyukiVoicies(ctx context.Context, obj *model.User, fields []*model.InputFields) ([]*model.HiroyukiVoice, error) {
	panic(fmt.Errorf("not implemented: HiroyukiVoicies - hiroyukiVoicies"))
}

// Exercise returns ExerciseResolver implementation.
func (r *Resolver) Exercise() ExerciseResolver { return &exerciseResolver{r} }

// Food returns FoodResolver implementation.
func (r *Resolver) Food() FoodResolver { return &foodResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type exerciseResolver struct{ *Resolver }
type foodResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *achievementResolver) IsClear(ctx context.Context, obj *model.MasterAchievement) (bool, error) {
	panic(fmt.Errorf("not implemented: IsClear - isClear"))
}
func (r *Resolver) Achievement() AchievementResolver { return &achievementResolver{r} }
type achievementResolver struct{ *Resolver }
*/
