package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"

	"github.com/moXXcha/hiroyuki_diet_API/graph/model"
)

// IsClear is the resolver for the isClear field.
func (r *achievementResolver) IsClear(ctx context.Context, obj *model.MasterAchievement) (bool, error) {
	panic(fmt.Errorf("not implemented: IsClear - isClear"))
}

// EstimateCalorie is the resolver for the estimateCalorie field.
func (r *foodResolver) EstimateCalorie(ctx context.Context, obj *model.Food) (int, error) {
	panic(fmt.Errorf("not implemented: EstimateCalorie - estimateCalorie"))
}

// LastUsedDate is the resolver for the lastUsedDate field.
func (r *foodResolver) LastUsedDate(ctx context.Context, obj *model.Food) (string, error) {
	date := obj.LastUsedDate.Format("2006-01-02")
	return date, nil
}

// IsUsing is the resolver for the isUsing field.
func (r *hiroyukiSkinResolver) IsUsing(ctx context.Context, obj *model.MasterHiroyukiSkin) (bool, error) {
	panic(fmt.Errorf("not implemented: IsUsing - isUsing"))
}

// IsHaving is the resolver for the isHaving field.
func (r *hiroyukiSkinResolver) IsHaving(ctx context.Context, obj *model.MasterHiroyukiSkin) (bool, error) {
	panic(fmt.Errorf("not implemented: IsHaving - isHaving"))
}

// Count is the resolver for the count field.
func (r *itemResolver) Count(ctx context.Context, obj *model.MasterItem) (int, error) {
	panic(fmt.Errorf("not implemented: Count - count"))
}

// TotalCalorie is the resolver for the totalCalorie field.
func (r *mealResolver) TotalCalorie(ctx context.Context, obj *model.Meal) (int, error) {
	panic(fmt.Errorf("not implemented: TotalCalorie - totalCalorie"))
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.Auth) (string, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Auth) (string, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// CreateExercise is the resolver for the createExercise field.
func (r *mutationResolver) CreateExercise(ctx context.Context, input model.InputExercise) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: CreateExercise - createExercise"))
}

// EditExercise is the resolver for the editExercise field.
func (r *mutationResolver) EditExercise(ctx context.Context, input model.InputExercise) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: EditExercise - editExercise"))
}

// ReceiptAchievement is the resolver for the receiptAchievement field.
func (r *mutationResolver) ReceiptAchievement(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: ReceiptAchievement - receiptAchievement"))
}

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.InputProfile) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: CreateProfile - createProfile"))
}

// EditProfile is the resolver for the editProfile field.
func (r *mutationResolver) EditProfile(ctx context.Context, input model.InputProfile) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: EditProfile - editProfile"))
}

// CreateMeal is the resolver for the createMeal field.
func (r *mutationResolver) CreateMeal(ctx context.Context, input model.InputMeal) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: CreateMeal - createMeal"))
}

// EditMeal is the resolver for the editMeal field.
func (r *mutationResolver) EditMeal(ctx context.Context, input model.InputMeal) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: EditMeal - editMeal"))
}

// PostSkin is the resolver for the postSkin field.
func (r *mutationResolver) PostSkin(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: PostSkin - postSkin"))
}

// UseItem is the resolver for the useItem field.
func (r *mutationResolver) UseItem(ctx context.Context, input model.UUID) (model.UUID, error) {
	panic(fmt.Errorf("not implemented: UseItem - useItem"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id model.UUID, usingSkin *bool, voiceField []*model.InputFields) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Foods is the resolver for the foods field.
func (r *queryResolver) Foods(ctx context.Context) ([]*model.Food, error) {
	db := r.DB
	food := model.Food{}
	foods, err := food.GetAll(db)
	return foods, err
}

// Profile is the resolver for the profile field.
func (r *userResolver) Profile(ctx context.Context, obj *model.User) (*model.Profile, error) {
	panic(fmt.Errorf("not implemented: Profile - profile"))
}

// Exercisies is the resolver for the exercisies field.
func (r *userResolver) Exercisies(ctx context.Context, obj *model.User) ([]*model.Exercise, error) {
	panic(fmt.Errorf("not implemented: Exercisies - exercisies"))
}

// Meals is the resolver for the meals field.
func (r *userResolver) Meals(ctx context.Context, obj *model.User) ([]*model.Meal, error) {
	panic(fmt.Errorf("not implemented: Meals - meals"))
}

// Items is the resolver for the items field.
func (r *userResolver) Items(ctx context.Context, obj *model.User) ([]*model.MasterItem, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}

// HiroyukiSkins is the resolver for the hiroyukiSkins field.
func (r *userResolver) HiroyukiSkins(ctx context.Context, obj *model.User) ([]*model.MasterHiroyukiSkin, error) {
	panic(fmt.Errorf("not implemented: HiroyukiSkins - hiroyukiSkins"))
}

// Achievements is the resolver for the achievements field.
func (r *userResolver) Achievements(ctx context.Context, obj *model.User) ([]*model.MasterAchievement, error) {
	panic(fmt.Errorf("not implemented: Achievements - achievements"))
}

// HiroyukiVoicies is the resolver for the hiroyukiVoicies field.
func (r *userResolver) HiroyukiVoicies(ctx context.Context, obj *model.User) ([]*model.HiroyukiVoice, error) {
	panic(fmt.Errorf("not implemented: HiroyukiVoicies - hiroyukiVoicies"))
}

// Achievement returns AchievementResolver implementation.
func (r *Resolver) Achievement() AchievementResolver { return &achievementResolver{r} }

// Food returns FoodResolver implementation.
func (r *Resolver) Food() FoodResolver { return &foodResolver{r} }

// HiroyukiSkin returns HiroyukiSkinResolver implementation.
func (r *Resolver) HiroyukiSkin() HiroyukiSkinResolver { return &hiroyukiSkinResolver{r} }

// Item returns ItemResolver implementation.
func (r *Resolver) Item() ItemResolver { return &itemResolver{r} }

// Meal returns MealResolver implementation.
func (r *Resolver) Meal() MealResolver { return &mealResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type achievementResolver struct{ *Resolver }
type foodResolver struct{ *Resolver }
type hiroyukiSkinResolver struct{ *Resolver }
type itemResolver struct{ *Resolver }
type mealResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Items(ctx context.Context) ([]*model.MasterItem, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}
func (r *queryResolver) HiroyukiSkins(ctx context.Context) ([]*model.MasterHiroyukiSkin, error) {
	panic(fmt.Errorf("not implemented: HiroyukiSkins - hiroyukiSkins"))
}
func (r *queryResolver) Achievements(ctx context.Context) ([]*model.MasterAchievement, error) {
	panic(fmt.Errorf("not implemented: Achievements - achievements"))
}
*/
